spring.application.name=FoodDelivery

#DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery
spring.datasource.username=JDBC
spring.datasource.password=JDBC

#JPA Config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#File Upload Configs
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#File Path
restaurant.banner.file.path=Uploads/Restaurants-Banner/

#Cloudinary credentials
cloudinary.cloud-name=drhjyjqs4
cloudinary.api-key=239122478486964
cloudinary.api-secret=cOihTC3fKKBIPsFFkRNJjgO4Zrg

#Cloudinary Configs
cloudinary.upload.default-folder=Uploads/
cloudinary.upload.allowed-formats=jpg,jpeg,png,gif,webp,pdf,mp4